"use client";

import { useState } from "react";

export default function ImagePage() {
  const [prompt, setPrompt] = useState("");
  const [image, setImage] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  async function generateImage(customPrompt?: string) {
    const finalPrompt = (customPrompt ?? prompt).trim();

    if (!finalPrompt || loading) return;

    setLoading(true);
    setError("");

    try {
      const response = await fetch("/api/image", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          prompt: finalPrompt,
        }),
      });

      const data = await response.json();

      if (!response.ok || !data.success) {
        throw new Error(data.error || "ساخت تصویر با خطا مواجه شد.");
      }

      setImage(data.image);
    } catch (err: any) {
      setError(err?.message || "خطایی هنگام ساخت تصویر رخ داد.");
    } finally {
      setLoading(false);
    }
  }

  function retry() {
    if (prompt.trim()) {
      generateImage(prompt);
    }
  }

  function downloadImage() {
    if (!image) return;

    const link = document.createElement("a");
    link.href = image;
    link.download = "mobixa-image.jpg";
    document.body.appendChild(link);
    link.click();
    link.remove();
  }

  return (
    <main className="image-page">
      <div className="background-glow glow-one" />
      <div className="background-glow glow-two" />

      <section className="image-container">

        {/* AI Orb */}
        <div className="ai-orb-wrap">
          <div className="ai-orbit orbit-one" />
          <div className="ai-orbit orbit-two" />

          <div className="ai-orb">
            <span>M</span>
          </div>
        </div>

        {/* Header */}
        <div className="header">
          <div className="eyebrow">
            MOBIXA IMAGE LAB
          </div>

          <h1>
            ایده بده،{" "}
            <span>تصویر تحویل بگیر</span>
          </h1>

          <p>
            ایده‌ات را بنویس؛ موبیکسا آن را به یک تصویر تبدیل می‌کند.
          </p>
        </div>

        {/* Prompt Box */}
        <div className={`prompt-box ${loading ? "is-loading" : ""}`}>

          <textarea
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
            placeholder="مثلاً: یک شهر آینده‌نگر در شب، با نورهای نئونی و باران..."
            maxLength={2048}
            disabled={loading}
            onKeyDown={(e) => {
              if (e.key === "Enter" && (e.ctrlKey || e.metaKey)) {
                e.preventDefault();
                generateImage();
              }
            }}
          />

          <div className="prompt-bottom">

            <span className="counter">
              {prompt.length}/2048
            </span>

            {/* Send Button */}
            <button
              className={`send-button ${loading ? "loading" : ""}`}
              onClick={() => generateImage()}
              disabled={!prompt.trim() || loading}
              aria-label="ساخت تصویر"
            >
              <span className="send-ring" />

              {loading ? (
                <span className="spinner" />
              ) : (
                <svg
                  viewBox="0 0 24 24"
                  width="21"
                  height="21"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="2"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                >
                  <path d="M22 2 11 13" />
                  <path d="m22 2-7 20-4-9-9-4Z" />
                </svg>
              )}
            </button>

          </div>
        </div>

        {/* Error */}
        {error && (
          <div className="error-box">
            <span>{error}</span>
          </div>
        )}

        {/* Result */}
        {image && (
          <section className="result-section">

            <div className="result-header">
              <div>
                <div className="result-label">
                  GENERATED IMAGE
                </div>

                <h2>
                  تصویرت آماده است
                </h2>
              </div>
            </div>

            <div className="image-card">
              <img
                src={image}
                alt="Generated by Mobixa AI"
              />
            </div>

            <div className="result-actions">

              <button
                className="action-button primary"
                onClick={downloadImage}
              >
                <svg
                  viewBox="0 0 24 24"
                  width="19"
                  height="19"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="2"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                >
                  <path d="M12 3v12" />
                  <path d="m7 10 5 5 5-5" />
                  <path d="M5 21h14" />
                </svg>

                دانلود تصویر
              </button>

              <button
                className="action-button"
                onClick={retry}
                disabled={loading}
              >
                <svg
                  viewBox="0 0 24 24"
                  width="19"
                  height="19"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="2"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                >
                  <path d="M20 11a8.1 8.1 0 0 0-15.5-2" />
                  <path d="M4 4v5h5" />
                  <path d="M4 13a8.1 8.1 0 0 0 15.5 2" />
                  <path d="M20 20v-5h-5" />
                </svg>

                ساخت دوباره
              </button>

            </div>
          </section>
        )}

      </section>

      <style jsx>{`
        .image-page {
          min-height: 100vh;
          position: relative;
          overflow: hidden;
          background:
            radial-gradient(
              circle at 50% 15%,
              rgba(124, 92, 255, 0.13),
              transparent 32%
            ),
            #050507;
          color: #fff;
          font-family: inherit;
          direction: rtl;
          padding: 70px 20px 100px;
        }

        .image-container {
          width: min(900px, 100%);
          margin: 0 auto;
          position: relative;
          z-index: 2;
        }

        .background-glow {
          position: absolute;
          width: 420px;
          height: 420px;
          border-radius: 50%;
          filter: blur(120px);
          opacity: 0.12;
          pointer-events: none;
        }

        .glow-one {
          top: 0;
          right: -180px;
          background: #765cff;
        }

        .glow-two {
          bottom: 0;
          left: -180px;
          background: #00c6ff;
        }

        /* AI Orb */

        .ai-orb-wrap {
          width: 72px;
          height: 72px;
          margin: 0 auto 25px;
          position: relative;
          display: flex;
          align-items: center;
          justify-content: center;
        }

        .ai-orb {
          width: 52px;
          height: 52px;
          border-radius: 17px;
          display: flex;
          align-items: center;
          justify-content: center;
          position: relative;
          z-index: 3;

          background:
            linear-gradient(
              145deg,
              rgba(255, 255, 255, 0.15),
              rgba(255, 255, 255, 0.035)
            );

          border: 1px solid rgba(255, 255, 255, 0.15);
          box-shadow:
            0 0 35px rgba(125, 92, 255, 0.3),
            inset 0 0 20px rgba(255, 255, 255, 0.04);

          backdrop-filter: blur(15px);
        }

        .ai-orb span {
          font-size: 22px;
          font-weight: 800;
          background: linear-gradient(135deg, #fff, #9f8cff);
          -webkit-background-clip: text;
          -webkit-text-fill-color: transparent;
        }

        .ai-orbit {
          position: absolute;
          border: 1px solid rgba(145, 125, 255, 0.28);
          border-radius: 50%;
          transform: rotate(-25deg);
        }

        .orbit-one {
          width: 70px;
          height: 30px;
        }

        .orbit-two {
          width: 30px;
          height: 70px;
        }

        /* Header */

        .header {
          text-align: center;
          margin-bottom: 38px;
        }

        .eyebrow {
          display: inline-block;
          font-size: 11px;
          letter-spacing: 3px;
          font-weight: 700;
          color: rgba(190, 180, 255, 0.75);
          margin-bottom: 14px;
          direction: ltr;
        }

        h1 {
          margin: 0;
          font-size: clamp(32px, 6vw, 55px);
          line-height: 1.2;
          font-weight: 850;
          letter-spacing: -1.5px;
        }

        h1 span {
          background: linear-gradient(
            110deg,
            #ffffff,
            #a493ff,
            #6ddcff
          );
          -webkit-background-clip: text;
          -webkit-text-fill-color: transparent;
        }

        .header p {
          margin: 16px auto 0;
          max-width: 530px;
          color: rgba(255, 255, 255, 0.48);
          font-size: 14px;
          line-height: 1.9;
        }

        /* Prompt */

        .prompt-box {
          border: 1px solid rgba(255, 255, 255, 0.1);
          background: rgba(255, 255, 255, 0.045);
          border-radius: 25px;
          padding: 17px;
          backdrop-filter: blur(22px);
          box-shadow:
            0 25px 70px rgba(0, 0, 0, 0.35),
            inset 0 1px rgba(255, 255, 255, 0.04);
          transition: border-color 0.25s ease;
        }

        .prompt-box:focus-within {
          border-color: rgba(145, 125, 255, 0.38);
        }

        .prompt-box textarea {
          width: 100%;
          min-height: 145px;
          resize: vertical;
          border: 0;
          outline: 0;
          background: transparent;
          color: #fff;
          font-family: inherit;
          font-size: 16px;
          line-height: 2;
          padding: 8px 7px;
          direction: rtl;
        }

        .prompt-box textarea::placeholder {
          color: rgba(255, 255, 255, 0.28);
        }

        .prompt-box textarea:disabled {
          opacity: 0.55;
        }

        .prompt-bottom {
          display: flex;
          align-items: center;
          justify-content: space-between;
          direction: ltr;
          padding-top: 9px;
        }

        .counter {
          direction: ltr;
          font-size: 11px;
          color: rgba(255, 255, 255, 0.28);
        }

        /* Send */

        .send-button {
          width: 53px;
          height: 53px;
          border-radius: 17px;
          border: 0;
          position: relative;
          display: flex;
          align-items: center;
          justify-content: center;
          cursor: pointer;
          color: #fff;
          background: linear-gradient(145deg, #735cff, #4d3ad9);
          box-shadow:
            0 8px 30px rgba(101, 76, 255, 0.32);
          overflow: visible;
        }

        .send-button:disabled {
          cursor: not-allowed;
          opacity: 0.35;
          box-shadow: none;
        }

        .send-button:not(:disabled):hover {
          transform: translateY(-1px);
        }

        .send-ring {
          position: absolute;
          inset: -5px;
          border-radius: 20px;
          border: 2px solid transparent;
          border-top-color: rgba(166, 150, 255, 0.95);
          border-right-color: rgba(115, 92, 255, 0.35);
          animation: rotate-ring 1.5s linear infinite;
          pointer-events: none;
        }

        @keyframes rotate-ring {
          to {
            transform: rotate(360deg);
          }
        }

        .spinner {
          width: 20px;
          height: 20px;
          border: 2px solid rgba(255, 255, 255, 0.3);
          border-top-color: #fff;
          border-radius: 50%;
          animation: spinner 0.75s linear infinite;
        }

        @keyframes spinner {
          to {
            transform: rotate(360deg);
          }
        }

        /* Result */

        .result-section {
          margin-top: 55px;
          animation: appear 0.45s ease both;
        }

        @keyframes appear {
          from {
            opacity: 0;
            transform: translateY(15px);
          }

          to {
            opacity: 1;
            transform: translateY(0);
          }
        }

        .result-header {
          margin-bottom: 18px;
        }

        .result-label {
          direction: ltr;
          font-size: 10px;
          letter-spacing: 2px;
          color: rgba(170, 155, 255, 0.7);
          margin-bottom: 6px;
        }

        .result-header h2 {
          margin: 0;
          font-size: 22px;
        }

        .image-card {
          overflow: hidden;
          border-radius: 25px;
          border: 1px solid rgba(255, 255, 255, 0.1);
          background: rgba(255, 255, 255, 0.035);
          box-shadow: 0 30px 80px rgba(0, 0, 0, 0.42);
        }

        .image-card img {
          display: block;
          width: 100%;
          height: auto;
        }

        .result-actions {
          display: flex;
          gap: 12px;
          margin-top: 16px;
        }

        .action-button {
          flex: 1;
          min-height: 52px;
          border-radius: 16px;
          border: 1px solid rgba(255, 255, 255, 0.1);
          background: rgba(255, 255, 255, 0.055);
          color: #fff;
          display: flex;
          align-items: center;
          justify-content: center;
          gap: 9px;
          cursor: pointer;
          font-family: inherit;
          font-size: 14px;
          font-weight: 700;
          transition:
            transform 0.2s ease,
            background 0.2s ease,
            border-color 0.2s ease;
        }

        .action-button:hover {
          transform: translateY(-1px);
          background: rgba(255, 255, 255, 0.09);
          border-color: rgba(255, 255, 255, 0.18);
        }

        .action-button.primary {
          background: linear-gradient(
            135deg,
            rgba(115, 92, 255, 0.95),
            rgba(82, 63, 210, 0.95)
          );
          border-color: transparent;
        }

        @media (max-width: 600px) {
          .image-page {
            padding: 45px 14px 70px;
          }

          h1 {
            font-size: 32px;
          }

          .header p {
            font-size: 13px;
          }

          .prompt-box {
            border-radius: 21px;
            padding: 13px;
          }

          .prompt-box textarea {
            min-height: 125px;
            font-size: 15px;
          }

          .result-actions {
            flex-direction: column;
          }

          .action-button {
            flex: none;
          }
        }
      `}</style>
    </main>
  );
}
